"""nth_dao.conformance — wire-protocol conformance test vectors.

Purpose: anyone implementing the NTH DAO protocol in another language
(Rust, Go, TypeScript, …) MUST be able to verify their implementation
against a fixed set of (input, expected-output) pairs.

This package ships:

    vectors.json     — canonical test vectors as JSON
    run_vectors.py   — Python reference runner that loads vectors.json
                       and asserts the Python implementation matches.

If a non-Python implementation passes every assertion in vectors.json
when implemented under their language's conformance harness, that
implementation is considered wire-compatible with the reference.

Coverage in v0.9.4 (foundational scope):
    1. canonical_json — byte-level equality of the canonical-JSON encoder
    2. Ed25519 signature & verification round-trip
    3. AgentIdentity.fingerprint
    4. Endorsement signing (canonical_json over signable_dict)
    5. Revocation signing
    6. Channel message signing
    7. TeamConfig owner_sig signing
    8. MissionTemplate publisher_sig
    9. MissionReview reviewer_sig
   10. Invitation owner signing
   11. Replay window enforcement

Vectors are generated by `python -m nth_dao.conformance.regenerate`.
Once written they MUST NOT change between releases unless we bump the
protocol version. The vectors file IS part of the wire format spec.
"""

from .runner import (
    ConformanceFailure,
    load_vectors,
    run_all_vectors,
)
from .external_vc import (
    ExternalVCResult,
    verify_with_didkit,
    verify_with_vcjs,
)

__all__ = [
    "ConformanceFailure",
    "ExternalVCResult",
    "load_vectors",
    "run_all_vectors",
    "verify_with_didkit",
    "verify_with_vcjs",
]
